"""empty message

Revision ID: 1265963ebc18
Revises: 8687cda202c7
Create Date: 2024-05-16 10:43:21.915935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1265963ebc18'
down_revision = '8687cda202c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=36), nullable=True),
    sa.Column('host_user_id', sa.Integer(), nullable=True),
    sa.Column('guest_username', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaboration')
    # ### end Alembic commands ###
