"""Added created_at to snippets

Revision ID: 5dbf89cf696e
Revises: 65ad1d9e3c4d
Create Date: 2024-02-02 22:39:53.227659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbf89cf696e'
down_revision = '65ad1d9e3c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snippet', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
