"""empty message

Revision ID: 75a78bebf601
Revises: 1265963ebc18
Create Date: 2024-05-16 11:18:50.756138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a78bebf601'
down_revision = '1265963ebc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('css_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('js_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration', schema=None) as batch_op:
        batch_op.drop_column('js_code')
        batch_op.drop_column('css_code')
        batch_op.drop_column('html_code')

    # ### end Alembic commands ###
