"""Initial migration.

Revision ID: f7731f5e8583
Revises: e10a30c555df
Create Date: 2024-05-16 13:19:09.663899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7731f5e8583'
down_revision = 'e10a30c555df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaboration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room', sa.VARCHAR(length=36), nullable=False),
    sa.Column('host_user_id', sa.INTEGER(), nullable=False),
    sa.Column('guest_username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('html_code', sa.TEXT(), nullable=True),
    sa.Column('css_code', sa.TEXT(), nullable=True),
    sa.Column('js_code', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room')
    )
    # ### end Alembic commands ###
